### PR TITLE
feat: Add the `cerrado` sequential colormap

### PR DESCRIPTION
**Pull request by apcamargo**
This PR adds the `cerrado` sequential colormap to the `contrib` namespace. This was created by interpolating three colors (`#6e2504`, `#e1344b`, and `#f3ccba`) with natural spline in the OKLAB space using the [`coloraide`](https://github.com/facelessuser/coloraide) library.

That's the last one of colormaps that I have to contribute for the meanwhile.

cerrado

### CODE REVIEW

**Review by tlambert03 — APPROVED** [review]
very nice,  thanks again for your contributions!

**Comment by apcamargo** [comment]
Happy to contribute!

I'm curious why the [perceptual lightness increases linearly in the documentation](https://cmap-docs.readthedocs.io/en/latest/catalog/sequential/contrib:cerrado/). Since I didn't use CAM02-UCS and the `viscm` plot above shows that the derivative of the perceptual lightness varies across the colormap, I was surprised to see that it is linear in the documentation.

**Comment by tlambert03** [comment]
If you're curious to see how it's generated, the code used to calculate the y values for that chart is in `_util.report` (it's the J key in the return dict).

**Comment by tlambert03** [comment]
Might be a javascript/chart issue actually... if you hover on the delta values they range very similarly to your data, between 50-60 or so

**Comment by apcamargo** [comment]
The perceptual lightness curve appears incorrect; it should exhibit a slight bump rather than being a straight line. However, I did not find any apparent issues with the code. Maybe the curves are there but it is very subtle.

**Comment by tlambert03** [comment]
i believe it's just the scaling of the Y axis:  hover over the values and you'll see that the deltas match the perceptual lightness derivative from your graph (ranging from ~50 to 60+ and then back down a bit):

Screenshot 2024-08-05 at 7 14 29 PM
Screenshot 2024-08-05 at 7 14 52 PM
Screenshot 2024-08-05 at 7 14 58 PM

I pinned the range of deltas (right Y axis) to -500 --> + 500 globally [right here](https://github.com/tlambert03/cmap/blob/c6a74dbcf29bddbebc3cc5f6cabc042863ec6c29/docs/javascripts/cmap_charts.js#L96-L110).  This was so that A) one could generally look at many colormaps and say "is this generally linear compared to the others" without having to carefully look at the Y axis and know what range other colormaps have, ... and so that B) the grid on the graph is clean

I can see that it gives the impression in your colormap of perfect linearity, while it is in fact, _slightly_ nonlinear.    But, relative to some others, it is indeed rather linear.  Open to suggestions if you'd like to suggest a new presentation option

**Comment by apcamargo** [comment]
Yeah, I think you're right. I don't have any suggestions, it looks pretty good as is. Other than changing the range of the right Y axis, I don't see any other way to "fix" this. Is there any reason you set a large interval there?

**Comment by tlambert03** [comment]
>  Is there any reason you set a large interval there?

that was what I was trying to explain above:

> This was so that A) one could generally look at many colormaps and say "is this generally linear compared to the others" without having to carefully look at the Y axis and know what range other colormaps have, ... and so that B) the grid on the graph is clean

to clarify: -500-+500 was a range that fit the the full range of deltas seen across *all* colormaps, so, for example, turbo covers a decent part of it:

Screenshot 2024-08-05 at 7 26 51 PM

 and others probably cover even more.

it does seem a bit random and large for a one-off linear colormap.  but that was the intention (to foster comparisons against others)

**Comment by apcamargo** [comment]
Ohh, I understand it now.

I don't see any reason for a change then. It's pretty good like this. I doubt such small deviations from a linear colormap are relevant enough to justify any changes.

**Comment by tlambert03** [comment]
Thanks for the eagle-eyed question :)

**Pull request merged**
